

services:
  mongodb:
    image: mongo:7.0
    container_name: p7_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./data:/data/import
    environment:
      - MONGO_INITDB_DATABASE=noscites
    restart: unless-stopped

volumes:
  mongodb_data:
